name: Generate Metrics Images

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: sankalpsinghcoder-ai
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          config_timezone: Asia/Kolkata

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics images"
          file_pattern: metrics.svg
